### ISSUE TITLE
Play-Button in Album View

### ISSUE THREAD

**Issue by canddoki** [orontee/argos#14]
Hello orontee,
thanks again for your really good work.
I don't no if it is an issue or I misunderstand something.
For the children the Album View (Library) is the main and easy tab. They choose an album and press the play button in the bottom right corner > music is playing > done. In there logic they press the button again and expect playback to stop or pause, but nothing happens.
Cheers and thank you very much

The following things are not issues, just thoughts of my first impressions ... or a small wishlist for programmer lazy times ;-).
- Two more CLI options: --hide-search (or --disable-search). If there is no keyboard, like in my case, the field is useless and --hide-volume-control. If someone, also like me :), have a physical volume control and disabled the softwaremixer in mopidy.conf don't need it.
- In Argus the default adress for Mopidy-http is set to 127.0.0.1:80. Perhaps you can set it to Mopidy's standard 127.0.0.1:**66**80, and in many cases Argus is running out of the box.

**Comment by orontee** [comment]
Thanks for your feedback!

For the playback button in the album view, pressing the button again is supposed to clear the tracklist and fill it again with the the album tracks. I you pressed it twice in short delay, you may not notice this since Mopidy may not have started playing the first song when the tracklist is cleared...

I don't think the second press should pause the playback since this button is available on all album page, even albums that aren't currently played!

May be the icon should be changed, any suggestion welcome. 

I created #15 and #16 for the implementation of the two options you suggested. 

The default value of `mopidy-base-url` has been updated through commit 9954acc.

**Comment by orontee** [comment]
@canddoki Both CLI arguments have been implemented on 16-setting-or-cli-argument-to-hide-volume-button branch. Needs some testing but looks good at first view.

**Comment by canddoki** [comment]
@orontee Wow, that was fast :). I'll test it tomorrow and give you feedback.
I'll have to look again because of the play button. To be honest, I still don't really get it ;-).

**Comment by canddoki** [comment]
@orontee Here is my experience from the weekend. The CLI argument to hide the search box and also the query of the software-mixer work perfectly.
The strange thing is, that every time I reboot, the Argos library is empty. I have to press 'update library' and the albums-view fills up. By the way, the 'update-library' provide an update of the Argus-Library and not a 'mopidy local scan', isn't it?
I have attached the log file. Maybe you can find something here.

[18-06-2022_argos_run-log-1.txt](https://github.com/orontee/argos/files/8938006/18-06-2022_argos_run-log-1.txt)

**Comment by orontee** [comment]
> @orontee Here is my experience from the weekend. The CLI argument to hide the search box and also the query of the software-mixer work perfectly. 

Good news!

> The strange thing is, that every time I reboot, the Argos library is empty. I have to press 'update library' and the albums-view fills up. 

This is unexpected: An automatic discovery of the library is performed every time the connection is established with Mopidy server; There's no serialization of the library on the host running Argos (due to lack of time and motivation: My 400 albums library + 50 Bandcamp albums and as much Podcasts is synchronized in a relative short time).

> By the way, the 'update-library' provide an update of the Argus-Library and not a 'mopidy local scan', isn't it?

I confirm (Argos not Argus :slightly_smiling_face: ).

> I have attached the log file. Maybe you can find something here.
> 
> [18-06-2022_argos_run-log-1.txt](https://github.com/orontee/argos/files/8938006/18-06-2022_argos_run-log-1.txt)

Thanks! I'll be back after I've had a look to this log.

**Comment by orontee** [comment]
Two questions:
- Have you tried to run Argos on a different host than the one running Mopidy server? Have you seen the same problem of empty library there?
- Does the log you send includes the logs generated after you pressed "update library"?

**Comment by orontee** [comment]
From the logs I noticed that

- The network is available at startup and the websocket connection is
  established: A synchronization workflow of Argos model is started.

- After the response to the JSON-RPC command 10 (
  `core.tracklist.get_tl_tracks()`) is received, there's a 4 minutes
  gap without any activity!! Then the network is disconnected.

- When the network is back (2 seconds later), the synchronization
  workflow starts again and after the response to the JSON-RPC command
  20 ( `core.tracklist.get_tl_tracks()`) is received, a network status
  change is notified once more!

- Three seconds later the BROWSE_ALBUMS internal message is sent (by
  hand?) and processed successfully.

So the open questions is what has happened during the 4 minutes gap!
No idea on my side at current time.

I suggest you tried with a stable network connection.

The relevant logs are
```
2022-06-18 23:06:36,962 EventLoopThread DEBUG: argos.ws - Received result of JSON-RPC command id 10
2022-06-18 23:06:36,973 MainThread DEBUG: argos.model.utils - Updating 'state' from 0 to <PlaybackState.STOPPED: 3>
2022-06-18 23:06:36,976 MainThread DEBUG: argos.model.utils - Updating 'time_position' from -1 to 0
2022-06-18 23:10:32,461 MainThread DEBUG: argos.model - Network monitor signal a network status change
2022-06-18 23:10:32,461 MainThread DEBUG: argos.model.utils - Updating 'network_available' from True to False
2022-06-18 23:10:32,461 MainThread DEBUG: argos.controllers.playback - Clearing track playback state since not connected
2022-06-18 23:10:32,461 MainThread DEBUG: argos.model.utils - Property 'current_tl_track_tlid' already equal to -1
...
2022-06-18 23:10:34,308 MainThread DEBUG: argos.model.utils - Updating 'network_available' from False to True
...
2022-06-18 23:10:34,344 EventLoopThread DEBUG: argos.ws - Sending JSON-RPC command 20 with method core.tracklist.get_tl_tracks
2022-06-18 23:10:34,346 EventLoopThread DEBUG: argos.ws - Received result of JSON-RPC command id 20
2022-06-18 23:10:35,146 MainThread DEBUG: argos.model - Network monitor signal a network status change
2022-06-18 23:10:35,147 MainThread DEBUG: argos.model.utils - Property 'network_available' already equal to True
2022-06-18 23:10:38,161 EventLoopThread DEBUG: argos.app - Dispatching message of type MessageType.BROWSE_ALBUMS
...
2022-06-18 23:10:38,250 EventLoopThread DEBUG: argos.controllers.albums - Found 50 albums in directory with URI 'local:directory'
...
2022-06-18 23:10:38,302 EventLoopThread DEBUG: argos.controllers.albums - Starting album images download...
2022-06-18 23:10:38,303 EventLoopThread DEBUG: argos.download - Download task created
2022-06-18 23:10:38,303 EventLoopThread DEBUG: argos.download - Starting 1 batch of downloads
2022-06-18 23:10:38,305 MainThread DEBUG: argos.widgets.albumswindow - Updating album list...
2022-06-18 23:10:38,461 ImagesThread DEBUG: argos.widgets.albumswindow - Updating album images...
```

Side note: I noticed that you have both the `file` Mopidy extension and the `local` Mopidy extension enabled on Mopidy server; My testing configuration has only the `local` extension and Argos doesn't support the `file` extension. It explains the following warning but it isn't related to your problem:
```
2022-06-18 23:10:38,193 EventLoopThread WARNING: argos.controllers.albums - Skipping unsupported directory with URI 'file:///media/Musik'
```

**Comment by canddoki** [comment]
@orontee
> ... realized that it simpler for my children to use the physical one on the amplifier.

Same situation, sometimes we just have to take a step 'back' :).

> This is expected: There's no serialization of the library on the host running Argos (due to lack of time and motivation: My 400 albums library + 50 Bandcamp albums and as much Podcasts is synchronized in a relative short time).

Good to know or well programmed :). I didn't notice any lag with the first version of Argos.

> I confirm (Argos not Argus 🙂 ).

Sorry, I will take care :-)

**Comment by canddoki** [comment]
> @canddoki Four (+1) questions

- No, I don't have that option at the moment.
- Yes, should be short before: _'2022-06-18 23:10:38,193 EventLoopThread WARNING: argos.controllers.albums - Skipping unsupported directory with URI 'file:///media/Musik'_'. Journalctl shows me at this time that x-systemd.automount was mounting the NAS-HDD to /media/Musik/ where mopidy-local expects the files. After that event Argos found 50 albums. Could be an indicator of a wifi-problem. I will check the logfiles.
- Operating system is Debian-based 'DietPi v8.5', I installed the ARMv7 32-bit image on a RPI 4b with 2GB RAM. Desktop environment is LXDE with autologon and Argos in ~/.config/lxsession/LXDE/autostart. DBus is installed and running. The network is established via wpa_supplicant. So network manager isn't available.
- Mopidy is running as a system service.
- I installed the deb package using your good instructions :). I built it last Saturday, so ist should be commit 5797eee.

**Comment by canddoki** [comment]
> @orontee From the logs I noticed that

Thank you very much for your really detailed feedback. I will test the network by the end of the week. Think I don't need Mopidy's file extension and will disable it.

**Comment by canddoki** [comment]
@orontee Good Morning, I did a test at the weekend, but unfortunately with same result. Wifi, SSH, Mopidy, all is running very well and without errors. In the logfile you can see until 23:49:16 Argos was working, after that I waited a bit, until I pressed the Library-update-button at 23:52:19 and the albums-view fills up. Hope you can find the cause.

[25-06-2022_argos_run-log-1.txt](https://github.com/orontee/argos/files/8990436/25-06-2022_argos_run-log-1.txt)

**Comment by orontee** [comment]
@canddoki Thanks for this new log file. It's clear there's a problem in the processing of `core.tracklist.get_tl_tracks`. I'll spend some time on this and at least improve the logs. 

In the meantime could you post the output of the following command just before you click the "Library update" button? It's a call to `core.tracklist.get_tl_tracks` done through `curl` (don't forget to adapt the URL!):
```
curl -i -H Content-Type\:\ application/json -XPOST http\://192.168.1.45/mopidy/rpc -d \{'
'\ \ \"jsonrpc\"\:\ \"2.0\"\,'
'\ \ \"id\"\:\ 1\,'
'\ \ \"method\"\:\ \"core.tracklist.get_tl_tracks\"\,'
'\ \ \"params\"\:\ \{'
'\ \ \}'
'\}'
'
```

**Comment by orontee** [comment]
I suspect that the property `tracklist_loaded` of the model instance is never set to `True`. This happens when the tracklist version is equal to -1. I don't know whether it's what happens but I just pushed a change that ensures that `tracklist_loaded` is updated whatever the version is (see efb30df ).

https://github.com/orontee/argos/blob/main/argos/model/__init__.py#L213

**Comment by canddoki** [comment]
@orontee First of all thank you for your enthusiastic effort.
I checked your new version and voilà it's working :).
I really didn't notice the black triangle. I'll look at that tomorrow. At the moment I can't play any music in the children's room ;).
This is my mopidy.config
```
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf config" as user mopidy
[core]
cache_dir = /mnt/dietpi_userdata/mopidy/cache
config_dir = /etc/mopidy
data_dir = /mnt/dietpi_userdata/mopidy/data
max_tracklist_length = 10000
restore_state = false
```
with the default setting = false. I'll try out 'true' when I get a chance.
Good night for the moment ...

**Comment by orontee** [comment]
@candokki I am closing this one. Feel free to open a new issue if there's still something unclear with the "play" buttons.

**Comment by canddoki** [comment]
@orontee Yes it's done and I'm ready satisfied with Argos. I like also your new preference dialog and the philosophy keep it as simple as possible. Honestly, I'm still not entirely clear on the play buttons on the album page. I've thought about it and will write you an idea next week. I'm curious what you think of it :).
